(* Created with the Wolfram Language : www.wolfram.com *)
<|"Status" -> "Full-native-layer exact-chart certificate", 
 "MathematicaVersion" -> "15.0.1 for Mac OS X ARM (64-bit) (July 2, 2026)", 
 "OrderCount" -> 12, "OneLoopCompositeHROrderCount" -> 0, 
 "TwoLoopGenericMRKHROrderCount" -> 0, "TwoLoopCompositeHROrderCount" -> 6, 
 "CompositeHROrders" -> {{1, 2, 3, 5, 4}, {1, 2, 4, 3, 5}, {1, 2, 4, 5, 3}, 
   {1, 2, 5, 3, 4}, {1, 3, 4, 2, 5}, {1, 3, 5, 2, 4}}, 
 "TopologyCriterionObserved" -> "HR iff p4 is attached to internal vertex 3 \
or 5 (the two four-valent vertices), within this 12-ordering two-loop seed \
scan", "OrderRows" -> {<|"Index" -> 1, "ExternalOrderAtVertices" -> 
     {1, 2, 3, 4, 5}, "CentralGluonVertex" -> 4, 
    "CentralGluonAtFourValentVertexQ" -> False, 
    "OneLoopCompositePreselectionSurvivors" -> 0, 
    "OneLoopCompositeHiddenRegions" -> 0, 
    "TwoLoopGenericMRKPreselectionSurvivors" -> 1, 
    "TwoLoopGenericMRKStagedCandidates" -> 0, 
    "TwoLoopGenericMRKHiddenRegions" -> 0, 
    "TwoLoopCompositePreselectionSurvivors" -> 0, 
    "TwoLoopCompositeStagedCandidates" -> 0, 
    "TwoLoopCompositeHiddenRegions" -> 0|>, <|"Index" -> 2, 
    "ExternalOrderAtVertices" -> {1, 2, 3, 5, 4}, "CentralGluonVertex" -> 5, 
    "CentralGluonAtFourValentVertexQ" -> True, 
    "OneLoopCompositePreselectionSurvivors" -> 0, 
    "OneLoopCompositeHiddenRegions" -> 0, 
    "TwoLoopGenericMRKPreselectionSurvivors" -> 3, 
    "TwoLoopGenericMRKStagedCandidates" -> 3, 
    "TwoLoopGenericMRKHiddenRegions" -> 0, 
    "TwoLoopCompositePreselectionSurvivors" -> 3, 
    "TwoLoopCompositeStagedCandidates" -> 3, 
    "TwoLoopCompositeHiddenRegions" -> 1|>, <|"Index" -> 3, 
    "ExternalOrderAtVertices" -> {1, 2, 4, 3, 5}, "CentralGluonVertex" -> 3, 
    "CentralGluonAtFourValentVertexQ" -> True, 
    "OneLoopCompositePreselectionSurvivors" -> 0, 
    "OneLoopCompositeHiddenRegions" -> 0, 
    "TwoLoopGenericMRKPreselectionSurvivors" -> 3, 
    "TwoLoopGenericMRKStagedCandidates" -> 3, 
    "TwoLoopGenericMRKHiddenRegions" -> 0, 
    "TwoLoopCompositePreselectionSurvivors" -> 3, 
    "TwoLoopCompositeStagedCandidates" -> 3, 
    "TwoLoopCompositeHiddenRegions" -> 1|>, <|"Index" -> 4, 
    "ExternalOrderAtVertices" -> {1, 2, 4, 5, 3}, "CentralGluonVertex" -> 3, 
    "CentralGluonAtFourValentVertexQ" -> True, 
    "OneLoopCompositePreselectionSurvivors" -> 0, 
    "OneLoopCompositeHiddenRegions" -> 0, 
    "TwoLoopGenericMRKPreselectionSurvivors" -> 3, 
    "TwoLoopGenericMRKStagedCandidates" -> 3, 
    "TwoLoopGenericMRKHiddenRegions" -> 0, 
    "TwoLoopCompositePreselectionSurvivors" -> 3, 
    "TwoLoopCompositeStagedCandidates" -> 3, 
    "TwoLoopCompositeHiddenRegions" -> 1|>, <|"Index" -> 5, 
    "ExternalOrderAtVertices" -> {1, 2, 5, 3, 4}, "CentralGluonVertex" -> 5, 
    "CentralGluonAtFourValentVertexQ" -> True, 
    "OneLoopCompositePreselectionSurvivors" -> 0, 
    "OneLoopCompositeHiddenRegions" -> 0, 
    "TwoLoopGenericMRKPreselectionSurvivors" -> 3, 
    "TwoLoopGenericMRKStagedCandidates" -> 3, 
    "TwoLoopGenericMRKHiddenRegions" -> 0, 
    "TwoLoopCompositePreselectionSurvivors" -> 3, 
    "TwoLoopCompositeStagedCandidates" -> 3, 
    "TwoLoopCompositeHiddenRegions" -> 1|>, <|"Index" -> 6, 
    "ExternalOrderAtVertices" -> {1, 2, 5, 4, 3}, "CentralGluonVertex" -> 4, 
    "CentralGluonAtFourValentVertexQ" -> False, 
    "OneLoopCompositePreselectionSurvivors" -> 0, 
    "OneLoopCompositeHiddenRegions" -> 0, 
    "TwoLoopGenericMRKPreselectionSurvivors" -> 1, 
    "TwoLoopGenericMRKStagedCandidates" -> 0, 
    "TwoLoopGenericMRKHiddenRegions" -> 0, 
    "TwoLoopCompositePreselectionSurvivors" -> 0, 
    "TwoLoopCompositeStagedCandidates" -> 0, 
    "TwoLoopCompositeHiddenRegions" -> 0|>, <|"Index" -> 7, 
    "ExternalOrderAtVertices" -> {1, 3, 2, 4, 5}, "CentralGluonVertex" -> 4, 
    "CentralGluonAtFourValentVertexQ" -> False, 
    "OneLoopCompositePreselectionSurvivors" -> 0, 
    "OneLoopCompositeHiddenRegions" -> 0, 
    "TwoLoopGenericMRKPreselectionSurvivors" -> 0, 
    "TwoLoopGenericMRKStagedCandidates" -> 0, 
    "TwoLoopGenericMRKHiddenRegions" -> 0, 
    "TwoLoopCompositePreselectionSurvivors" -> 0, 
    "TwoLoopCompositeStagedCandidates" -> 0, 
    "TwoLoopCompositeHiddenRegions" -> 0|>, <|"Index" -> 8, 
    "ExternalOrderAtVertices" -> {1, 3, 2, 5, 4}, "CentralGluonVertex" -> 5, 
    "CentralGluonAtFourValentVertexQ" -> True, 
    "OneLoopCompositePreselectionSurvivors" -> 0, 
    "OneLoopCompositeHiddenRegions" -> 0, 
    "TwoLoopGenericMRKPreselectionSurvivors" -> 0, 
    "TwoLoopGenericMRKStagedCandidates" -> 0, 
    "TwoLoopGenericMRKHiddenRegions" -> 0, 
    "TwoLoopCompositePreselectionSurvivors" -> 0, 
    "TwoLoopCompositeStagedCandidates" -> 0, 
    "TwoLoopCompositeHiddenRegions" -> 0|>, <|"Index" -> 9, 
    "ExternalOrderAtVertices" -> {1, 3, 4, 2, 5}, "CentralGluonVertex" -> 3, 
    "CentralGluonAtFourValentVertexQ" -> True, 
    "OneLoopCompositePreselectionSurvivors" -> 0, 
    "OneLoopCompositeHiddenRegions" -> 0, 
    "TwoLoopGenericMRKPreselectionSurvivors" -> 3, 
    "TwoLoopGenericMRKStagedCandidates" -> 3, 
    "TwoLoopGenericMRKHiddenRegions" -> 0, 
    "TwoLoopCompositePreselectionSurvivors" -> 3, 
    "TwoLoopCompositeStagedCandidates" -> 3, 
    "TwoLoopCompositeHiddenRegions" -> 1|>, <|"Index" -> 10, 
    "ExternalOrderAtVertices" -> {1, 3, 5, 2, 4}, "CentralGluonVertex" -> 5, 
    "CentralGluonAtFourValentVertexQ" -> True, 
    "OneLoopCompositePreselectionSurvivors" -> 0, 
    "OneLoopCompositeHiddenRegions" -> 0, 
    "TwoLoopGenericMRKPreselectionSurvivors" -> 3, 
    "TwoLoopGenericMRKStagedCandidates" -> 3, 
    "TwoLoopGenericMRKHiddenRegions" -> 0, 
    "TwoLoopCompositePreselectionSurvivors" -> 3, 
    "TwoLoopCompositeStagedCandidates" -> 3, 
    "TwoLoopCompositeHiddenRegions" -> 1|>, <|"Index" -> 11, 
    "ExternalOrderAtVertices" -> {1, 4, 2, 3, 5}, "CentralGluonVertex" -> 2, 
    "CentralGluonAtFourValentVertexQ" -> False, 
    "OneLoopCompositePreselectionSurvivors" -> 0, 
    "OneLoopCompositeHiddenRegions" -> 0, 
    "TwoLoopGenericMRKPreselectionSurvivors" -> 0, 
    "TwoLoopGenericMRKStagedCandidates" -> 0, 
    "TwoLoopGenericMRKHiddenRegions" -> 0, 
    "TwoLoopCompositePreselectionSurvivors" -> 0, 
    "TwoLoopCompositeStagedCandidates" -> 0, 
    "TwoLoopCompositeHiddenRegions" -> 0|>, <|"Index" -> 12, 
    "ExternalOrderAtVertices" -> {1, 4, 3, 2, 5}, "CentralGluonVertex" -> 2, 
    "CentralGluonAtFourValentVertexQ" -> False, 
    "OneLoopCompositePreselectionSurvivors" -> 0, 
    "OneLoopCompositeHiddenRegions" -> 0, 
    "TwoLoopGenericMRKPreselectionSurvivors" -> 1, 
    "TwoLoopGenericMRKStagedCandidates" -> 0, 
    "TwoLoopGenericMRKHiddenRegions" -> 0, 
    "TwoLoopCompositePreselectionSurvivors" -> 0, 
    "TwoLoopCompositeStagedCandidates" -> 0, 
    "TwoLoopCompositeHiddenRegions" -> 0|>}, "RepresentativeCertificate" -> 
  <|"ExternalOrderAtVertices" -> {1, 2, 3, 5, 4}, 
   "AlignedSuperleadingPolynomial" -> K*M^2*P*(-(P*x2) + K*x3)*
     (x1*x4 - x0*x5), "CancellationGenerator" -> 
    {-((P*x2 - K*x3)*(x1*x4 - x0*x5))}, "FaceScaling" -> 
    <|x0 -> -3, x1 -> -3, x2 -> 0, x3 -> -3, x4 -> -3, x5 -> -3|>, 
   "HRFScaling" -> <|x0 -> -1, x1 -> -1, x2 -> -1, x3 -> -1, x4 -> -1, 
     x5 -> -1|>, "TotalScaling" -> <|x0 -> -4, x1 -> -4, x2 -> -1, x3 -> -4, 
     x4 -> -4, x5 -> -4|>, "RelativeTotalScaling" -> 
    <|x0 -> -3, x1 -> -3, x2 -> 0, x3 -> -3, x4 -> -3, x5 -> -3|>, 
   "WSL" -> -9, "WHR" -> -8, "HierarchyGap" -> 1, "ResolvedFacetRank" -> 6, 
   "RequiredFacetRank" -> 6, "AuditStatus" -> "AcceptedLowerFacet", 
   "CertificationVectorSource" -> "StagedAsymptoticOrderAlignmentPlusHRF"|>, 
 "RateChecks" -> {<|"ExternalOrderAtVertices" -> {1, 2, 3, 5, 4}, "a" -> 1, 
    "b" -> 2, "p4PowerOverMRKPower" -> 1/2, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 2, 4, 3, 5}, "a" -> 1, "b" -> 2, 
    "p4PowerOverMRKPower" -> 1/2, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 2, 4, 5, 3}, "a" -> 1, "b" -> 2, 
    "p4PowerOverMRKPower" -> 1/2, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 2, 5, 3, 4}, "a" -> 1, "b" -> 2, 
    "p4PowerOverMRKPower" -> 1/2, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 3, 4, 2, 5}, "a" -> 1, "b" -> 2, 
    "p4PowerOverMRKPower" -> 1/2, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 3, 5, 2, 4}, "a" -> 1, "b" -> 2, 
    "p4PowerOverMRKPower" -> 1/2, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 2, 3, 5, 4}, "a" -> 1, "b" -> 3, 
    "p4PowerOverMRKPower" -> 1/3, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 2, 4, 3, 5}, "a" -> 1, "b" -> 3, 
    "p4PowerOverMRKPower" -> 1/3, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 2, 4, 5, 3}, "a" -> 1, "b" -> 3, 
    "p4PowerOverMRKPower" -> 1/3, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 2, 5, 3, 4}, "a" -> 1, "b" -> 3, 
    "p4PowerOverMRKPower" -> 1/3, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 3, 4, 2, 5}, "a" -> 1, "b" -> 3, 
    "p4PowerOverMRKPower" -> 1/3, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 3, 5, 2, 4}, "a" -> 1, "b" -> 3, 
    "p4PowerOverMRKPower" -> 1/3, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 2, 3, 5, 4}, "a" -> 2, "b" -> 3, 
    "p4PowerOverMRKPower" -> 2/3, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 2, 4, 3, 5}, "a" -> 2, "b" -> 3, 
    "p4PowerOverMRKPower" -> 2/3, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 2, 4, 5, 3}, "a" -> 2, "b" -> 3, 
    "p4PowerOverMRKPower" -> 2/3, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 2, 5, 3, 4}, "a" -> 2, "b" -> 3, 
    "p4PowerOverMRKPower" -> 2/3, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 3, 4, 2, 5}, "a" -> 2, "b" -> 3, 
    "p4PowerOverMRKPower" -> 2/3, "HiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 3, 5, 2, 4}, "a" -> 2, "b" -> 3, 
    "p4PowerOverMRKPower" -> 2/3, "HiddenRegionCount" -> 1|>}, 
 "TransverseSignChecks" -> {<|"ExternalOrderAtVertices" -> {1, 2, 3, 5, 4}, 
    "PlusChartHiddenRegionCount" -> 1, "MinusChartHiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 2, 4, 3, 5}, 
    "PlusChartHiddenRegionCount" -> 1, "MinusChartHiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 2, 4, 5, 3}, 
    "PlusChartHiddenRegionCount" -> 1, "MinusChartHiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 2, 5, 3, 4}, 
    "PlusChartHiddenRegionCount" -> 1, "MinusChartHiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 3, 4, 2, 5}, 
    "PlusChartHiddenRegionCount" -> 1, "MinusChartHiddenRegionCount" -> 1|>, 
   <|"ExternalOrderAtVertices" -> {1, 3, 5, 2, 4}, 
    "PlusChartHiddenRegionCount" -> 1, "MinusChartHiddenRegionCount" -> 1|>}|>
