(* Created with the Wolfram Language : www.wolfram.com *)
{<|"ExternalOrderAtVertices" -> {1, 2, 3, 4, 5}, "Mode" -> "Adaptive", 
  "HiddenRegionQ" -> False, "HiddenRegionCount" -> 0, 
  "SearchTruncatedQ" -> False, "SearchCompleteQ" -> True, 
  "CandidateGeneratorCount" -> Missing["Absent"], "Generators" -> {}, 
  "RegionVectors" -> {}, "ObstructionData" -> Missing["NoObstructionFound", 
    Automatic]|>, <|"ExternalOrderAtVertices" -> {1, 2, 3, 5, 4}, 
  "Mode" -> "Adaptive", "HiddenRegionQ" -> False, "HiddenRegionCount" -> 0, 
  "SearchTruncatedQ" -> False, "SearchCompleteQ" -> True, 
  "CandidateGeneratorCount" -> Missing["Absent"], "Generators" -> {}, 
  "RegionVectors" -> {}, "ObstructionData" -> Missing["NoObstructionFound", 
    Automatic]|>, <|"ExternalOrderAtVertices" -> {1, 2, 4, 3, 5}, 
  "Mode" -> "Adaptive", "HiddenRegionQ" -> False, "HiddenRegionCount" -> 0, 
  "SearchTruncatedQ" -> False, "SearchCompleteQ" -> True, 
  "CandidateGeneratorCount" -> Missing["Absent"], "Generators" -> {}, 
  "RegionVectors" -> {}, "ObstructionData" -> Missing["NoObstructionFound", 
    Automatic]|>, <|"ExternalOrderAtVertices" -> {1, 2, 4, 5, 3}, 
  "Mode" -> "Adaptive", "HiddenRegionQ" -> False, "HiddenRegionCount" -> 0, 
  "SearchTruncatedQ" -> False, "SearchCompleteQ" -> True, 
  "CandidateGeneratorCount" -> Missing["Absent"], "Generators" -> {}, 
  "RegionVectors" -> {}, "ObstructionData" -> Missing["NoObstructionFound", 
    Automatic]|>, <|"ExternalOrderAtVertices" -> {1, 2, 5, 3, 4}, 
  "Mode" -> "Adaptive", "HiddenRegionQ" -> False, "HiddenRegionCount" -> 0, 
  "SearchTruncatedQ" -> False, "SearchCompleteQ" -> True, 
  "CandidateGeneratorCount" -> Missing["Absent"], "Generators" -> {}, 
  "RegionVectors" -> {}, "ObstructionData" -> Missing["NoObstructionFound", 
    Automatic]|>, <|"ExternalOrderAtVertices" -> {1, 2, 5, 4, 3}, 
  "Mode" -> "Adaptive", "HiddenRegionQ" -> False, "HiddenRegionCount" -> 0, 
  "SearchTruncatedQ" -> False, "SearchCompleteQ" -> True, 
  "CandidateGeneratorCount" -> Missing["Absent"], "Generators" -> {}, 
  "RegionVectors" -> {}, "ObstructionData" -> Missing["NoObstructionFound", 
    Automatic]|>, <|"ExternalOrderAtVertices" -> {1, 3, 2, 4, 5}, 
  "Mode" -> "Adaptive", "HiddenRegionQ" -> False, "HiddenRegionCount" -> 0, 
  "SearchTruncatedQ" -> False, "SearchCompleteQ" -> True, 
  "CandidateGeneratorCount" -> Missing["Absent"], "Generators" -> {}, 
  "RegionVectors" -> {}, "ObstructionData" -> Missing["NoObstructionFound", 
    Automatic]|>, <|"ExternalOrderAtVertices" -> {1, 3, 2, 5, 4}, 
  "Mode" -> "Adaptive", "HiddenRegionQ" -> False, "HiddenRegionCount" -> 0, 
  "SearchTruncatedQ" -> False, "SearchCompleteQ" -> True, 
  "CandidateGeneratorCount" -> Missing["Absent"], "Generators" -> {}, 
  "RegionVectors" -> {}, "ObstructionData" -> Missing["NoObstructionFound", 
    Automatic]|>, <|"ExternalOrderAtVertices" -> {1, 3, 4, 2, 5}, 
  "Mode" -> "Adaptive", "HiddenRegionQ" -> False, "HiddenRegionCount" -> 0, 
  "SearchTruncatedQ" -> False, "SearchCompleteQ" -> True, 
  "CandidateGeneratorCount" -> Missing["Absent"], "Generators" -> {}, 
  "RegionVectors" -> {}, "ObstructionData" -> Missing["NoObstructionFound", 
    Automatic]|>, <|"ExternalOrderAtVertices" -> {1, 3, 5, 2, 4}, 
  "Mode" -> "Adaptive", "HiddenRegionQ" -> False, "HiddenRegionCount" -> 0, 
  "SearchTruncatedQ" -> False, "SearchCompleteQ" -> True, 
  "CandidateGeneratorCount" -> Missing["Absent"], "Generators" -> {}, 
  "RegionVectors" -> {}, "ObstructionData" -> Missing["NoObstructionFound", 
    Automatic]|>, <|"ExternalOrderAtVertices" -> {1, 4, 2, 3, 5}, 
  "Mode" -> "Adaptive", "HiddenRegionQ" -> False, "HiddenRegionCount" -> 0, 
  "SearchTruncatedQ" -> False, "SearchCompleteQ" -> True, 
  "CandidateGeneratorCount" -> Missing["Absent"], "Generators" -> {}, 
  "RegionVectors" -> {}, "ObstructionData" -> Missing["NoObstructionFound", 
    Automatic]|>, <|"ExternalOrderAtVertices" -> {1, 4, 3, 2, 5}, 
  "Mode" -> "Adaptive", "HiddenRegionQ" -> False, "HiddenRegionCount" -> 0, 
  "SearchTruncatedQ" -> False, "SearchCompleteQ" -> True, 
  "CandidateGeneratorCount" -> Missing["Absent"], "Generators" -> {}, 
  "RegionVectors" -> {}, "ObstructionData" -> Missing["NoObstructionFound", 
    Automatic]|>}
